### ISSUE TITLE
Clarification: Empty fields

### ISSUE THREAD

**Issue by nickgirardo** [bigbass1997/TASD-Spec#2]
I want to confirm my expectation on what it means for a field to be "empty"

As an example, below is a packet I believe to be correctly formed:
```
      +=========+----------+==========+========================+
      | Key (A) | PEXP (N) | PLEN (N) | Payload (A)            |
                                      | Console (A) | Name (S) |
      | 00 01   | 01       | 01       | 01          |          |
      +=========+----------+==========+========================+

00 01 to set packet type to Console Name
01 for 1 byte long length
01 for 1 byte long payload
01 for NES
``` 

Is this how empty fields should be handled? This is to say, 0 bytes are allocated for them in the packet length and they are not represented. The fields are essentially omitted

**Comment by bigbass1997** [comment]
Yep that's correct.
